apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      # - name: multitool
      #   image: multitool
        # ports:
        # - contanerPort: 8080
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
