apiVersion: v1
kind: Service
metadata:
  name: mysvc2
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      port: 1180
      targetPort: 1180
      port: 11443
      targetPort: 11443
